from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import StringField, PasswordField, SubmitField, RadioField, IntegerField, FileField
from wtforms.validators import DataRequired, EqualTo, Optional

class Registration(FlaskForm):

    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    age = IntegerField(label='Age', default=0, validators=[Optional()])
    gender = RadioField(label='Gender', choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], coerce=int,
                        validators=[Optional()])
    photo = FileField('Photo', validators=[FileAllowed(['jpg', 'png'], 'Images only!')])

    args = {'choices': [(1, 'strongly disagree'), (2, 'disagree'), (3, 'neither disagree nor agree'),
                        (4, 'agree'), (5, 'strongly agree')],
            'coerce': int, 'validators': [Optional()]}
    A7 = RadioField(label='I take time out for others.', **args)
    B11 = RadioField(label='I know that I am not a special person.', **args)
    D5 = RadioField(label='I take control of things.', **args)
    P9 = RadioField(label='I try to forgive and forget.', **args)
    G10 = RadioField(label='I keep in the background.',  **args)
    N10 = RadioField(label="I can't do without the company of others.",  **args)
    I8 = RadioField(label='I trust others.', **args)
    C5 = RadioField(label='I am not easily frustrated.', **args)
    A5 = RadioField(label='I cheer people up.', **args)
    G7 = RadioField(label='I often feel uncomfortable around others.', **args)
    C1 = RadioField(label='I seldom feel blue.', **args)
    C8 = RadioField(label='I dislike myself.', **args)
    D1 = RadioField(label='I take charge.', **args)
    D9 = RadioField(label='I let others make the decisions.', **args)
    M1 = RadioField(label='I believe in the importance of art.', **args)
    J2 = RadioField(label='I like to get lost in thought.', **args)
    D7 = RadioField(label='I wait for others to lead the way.', **args)
    K10 = RadioField(label='I am willing to talk about myself.',  **args)
    G6 = RadioField(label='I find it difficult to approach others.', **args)
    N7 = RadioField(label='I enjoy my privacy.', **args)
    J5 = RadioField(label='I swim against the current.', **args)
    L6 = RadioField(label='I feel guilty when I say "no."', **args)
    K2 = RadioField(label='I am hard to get to know.', **args)
    K3 = RadioField(label="I don't talk a lot.", **args)
    F3 = RadioField(label="I believe in one true religion.", **args)
    P8 = RadioField(label='I am not easily annoyed.', **args)
    L7 = RadioField(label='I feel crushed by setbacks.', **args)
    L1 = RadioField(label='I am afraid that I will do the wrong thing.', **args)
    E4 = RadioField(label='I enjoy being part of a loud crowd.', **args)
    B8 = RadioField(label='I weigh the pros against the cons.', **args)
    J7 = RadioField(label='I do unexpected things.', **args)
    P2 = RadioField(label='I get angry easily.', **args)
    G9 = RadioField(label='I am quiet around strangers.', **args)
    N5 = RadioField(label="I don't mind eating alone.", **args)
    A6 = RadioField(label='I make people feel at ease.', **args)
    B4 = RadioField(label='I use my brain.', **args)
    P10 = RadioField(label='I have a good word for everyone.',  **args)
    C9 = RadioField(label='I feel desperate.', **args)
    D2 = RadioField(label='I want to be in charge.', **args)
    G1 = RadioField(label='I feel comfortable around people.', **args)
    E1 = RadioField(label='I am the life of the party.', **args)
    L10 = RadioField(label="I don't let others discourage me.", **args)
    N8 = RadioField(label='I enjoy being part of a group.', **args)
    J4 = RadioField(label='I love to daydream.', **args)
    I4 = RadioField(label='I distrust people.', **args)
    L4 = RadioField(label='I worry about things.', **args)
    L9 = RadioField(label='I am not easily bothered by things.', **args)
    F4 = RadioField(label='I respect authority.', **args)
    J1 = RadioField(label='I do things that others find strange.', **args)
    B13 = RadioField(label='I skip difficult words while reading.', **args)
    C2 = RadioField(label='I feel comfortable with myself.', **args)
    O5 = RadioField(label='I am exacting in my work.', **args)
    B3 = RadioField(label='I tend to analyze things.', **args)
    O4 = RadioField(label='I continue until everything is perfect.', **args)
    I10 = RadioField(label='I believe that people are basically moral.', **args)
    P3 = RadioField(label='I am quick to judge others.', **args)
    C4 = RadioField(label='I am relaxed most of the time.', **args)
    N6 = RadioField(label='I enjoy silence.', **args)
    K9 = RadioField(label='I show my feelings.', **args)
    P7 = RadioField(label='I judge people by their appearance.', **args)
    M5 = RadioField(label='I prefer variety to routine.', **args)
    D8 = RadioField(label='I never challenge things.', **args)
    P6 = RadioField(label="I can't stand being contradicted.", **args)
    A10 = RadioField(label='I try not to think about the needy.', **args)
    P5 = RadioField(label='I am easily put out.', **args)
    N2 = RadioField(label='I prefer to do things by myself.', **args)
    P1 = RadioField(label='I get irritated easily.', **args)
    B2 = RadioField(label='I know the answers to many questions.', **args)
    I7 = RadioField(label='I trust what people say.', **args)
    F5 = RadioField(label='I like to stand during the national anthem.', **args)
    H6 = RadioField(label='I love flowers.', **args)
    I1 = RadioField(label='I find it hard to forgive others.', **args)
    O9 = RadioField(label='I leave my belongings around.', **args)
    A3 = RadioField(label="I feel other's emotions.", **args)
    D10 = RadioField(label='I let myself be pushed around.', **args)
    E8 = RadioField(label="I don't like crowded events.", **args)
    M3 = RadioField(label='I enjoy hearing new ideas.', **args)
    E6 = RadioField(label='I act wild and crazy.', **args)
    H3 = RadioField(label='I read a lot.', **args)
    F2 = RadioField(label='I try to follow the rules.', **args)
    J3 = RadioField(label='I enjoy wild flights of fantasy.', **args)
    F8 = RadioField(label='I use swear words.', **args)
    L8 = RadioField(label="I don't worry about things that have already happened.", **args)
    D3 = RadioField(label='I say what I think.', **args)
    L3 = RadioField(label='I am easily hurt.', **args)
    N3 = RadioField(label='I enjoy spending time by myself.', **args)
    G3 = RadioField(label="I don't mind being the center of attention.", **args)
    J10 = RadioField(label='I seldom get lost in thought.', **args)
    J9 = RadioField(label='I seldom daydream.', **args)
    I2 = RadioField(label='I suspect hidden motives in others.', **args)
    M9 = RadioField(label='I am not interested in abstract ideas.', **args)
    C10 = RadioField(label='I am easily discouraged.', **args)
    D4 = RadioField(label='I am not afraid of providing criticism.', **args)
    K8 = RadioField(label='I disclose my intimate thoughts.', **args)
    H4 = RadioField(label="I don't like action movies.", **args)
    O1 = RadioField(label='I want everything to be "just right."', **args)
    L2 = RadioField(label='I feel threatened easily.', **args)
    E9 = RadioField(label='I am the last to laugh at a joke.', **args)
    H2 = RadioField(label='I enjoy discussing movies and books with others.', **args)
    E3 = RadioField(label='I joke around a lot.', **args)
    B12 = RadioField(label='I have a poor vocabulary.', **args)
    E10 = RadioField(label='I dislike loud music.', **args)
    B1 = RadioField(label='I make insightful remarks.', **args)
    A2 = RadioField(label='I enjoy bringing people together.', **args)
    O2 = RadioField(label='I get chores done right away.', **args)
    B7 = RadioField(label='I reflect on things before acting.', **args)
    O7 = RadioField(label='I am not bothered by disorder.', **args)
    A8 = RadioField(label="I don't like to get involved in other people's problems.", **args)
    F7 = RadioField(label='I break rules.', **args)
    D6 = RadioField(label='I can take strong measures.', **args)
    E2 = RadioField(label='I love large parties.', **args)
    H8 = RadioField(label='I do not like poetry.', **args)
    I9 = RadioField(label='I believe that others have good intentions.', **args)
    O8 = RadioField(label='I leave a mess in my room.', **args)
    O10 = RadioField(label='I put off unpleasant tasks.', **args)
    F9 = RadioField(label='I oppose authority.', **args)
    F6 = RadioField(label='I resist authority.', **args)
    C3 = RadioField(label='I readily overcome setbacks.', **args)
    B10 = RadioField(label='I get confused easily.', **args)
    A1 = RadioField(label='I know how to comfort others.', **args)
    K6 = RadioField(label='I am open about myself to others.', **args)
    H10 = RadioField(label='I rarely notice my emotional reactions.', **args)
    E5 = RadioField(label='I amuse my friends.', **args)
    M2 = RadioField(label='I love to think up new ways of doing things.', **args)
    H9 = RadioField(label='I dislike works of fiction.', **args)
    H7 = RadioField(label='I do not enjoy watching dance performances.', **args)
    G5 = RadioField(label='I start conversations.', **args)
    G4 = RadioField(label='I make friends easily.', **args)
    C7 = RadioField(label='I often feel blue.', **args)
    B6 = RadioField(label="I counter others' arguments.", **args)
    M8 = RadioField(label='I am not interested in theoretical discussions.', **args)
    N4 = RadioField(label='I seek quiet.', **args)
    C6 = RadioField(label='I have frequent mood swings.', **args)
    B5 = RadioField(label='I learn quickly.', **args)
    M7 = RadioField(label='I rarely look for a deeper meaning in things.', **args)
    H1 = RadioField(label='I like to read.', **args)
    K5 = RadioField(label='I keep my thoughts to myself.', **args)
    M10 = RadioField(label='I try to avoid complex people.', **args)
    K1 = RadioField(label='I reveal little about myself.', **args)
    O6 = RadioField(label='I am not bothered by messy people.', **args)
    B9 = RadioField(label='I consider myself an average person.', **args)
    O3 = RadioField(label='I like order.', **args)
    M6 = RadioField(label='I avoid philosophical discussions.', **args)
    P4 = RadioField(label="I am annoyed by others' mistakes.", **args)
    H5 = RadioField(label='I cry during movies.', **args)
    A9 = RadioField(label='I am not really interested in others.', **args)
    I6 = RadioField(label='I believe that people are essentially evil.', **args)
    F10 = RadioField(label='I know how to get around the rules.', **args)
    E7 = RadioField(label='I seldom joke around.', **args)
    M4 = RadioField(label='I carry the conversation to a higher level.', **args)
    L5 = RadioField(label='I spend time thinking about past mistakes.', **args)
    G2 = RadioField(label='I talk to a lot of different people at parties.', **args)
    K4 = RadioField(label='I bottle up my feelings.', **args)
    N1 = RadioField(label='I want to be left alone.', **args)
    A4 = RadioField(label="I take an interest in other people's lives.", **args)
    I3 = RadioField(label='I am wary of others.', **args)
    N9 = RadioField(label='I enjoy teamwork.', **args)
    G8 = RadioField(label='I have little to say.', **args)
    F1 = RadioField(label='I believe laws should be strictly enforced.', **args)
    J8 = RadioField(label='I do things by the book.', **args)
    K7 = RadioField(label='I am open about my feelings.', **args)
    I5 = RadioField(label='I believe that people seldom tell you the whole truth.', **args)
    J6 = RadioField(label='I take deviant positions.', **args)

    submit = SubmitField('Register')


# login setup
class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign in')